version: "3"

services:
  db:
    image: postgres:12 
    environment:
      - POSTGRES_DB=express-ts
      - POSTGRES_USER=postgres-api
      - POSTGRES_PASSWORD=secret


  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=express-ts
      - POSTGRES_USER=postgres-api
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST=db